/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package advanceprogramming;

import DatabaseFile.Customer;
import DatabaseFile.Service;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.UIManager;

/**
 *
 * @author Dacorie Smith
 */
public class GUI extends javax.swing.JFrame {
    
    DatabaseFunctions Db = new DatabaseFunctions();
    List<Customer> customer =Db.RetrieveAllCustomers();
    int Counter = customer.size()-1;//Use to keep track of which customer is next
    
    public Customer CurrentCustomer()
    { return customer.get(Counter); } // return the track of the current customer
    public void KeepCustomerCurrent()
    {customer =Db.RetrieveAllCustomers();}
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Inactive = new javax.swing.JRadioButton();
        Active = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        Deletlebtn = new javax.swing.JButton();
        Insertbtn = new javax.swing.JButton();
        Updatebtn = new javax.swing.JButton();
        Selectbtn = new javax.swing.JButton();
        Allbtn = new javax.swing.JButton();
        FirstNametxt = new javax.swing.JTextField();
        Sbox = new javax.swing.JComboBox();
        Surnametxt = new javax.swing.JTextField();
        Idtxt = new javax.swing.JTextField();
        SuccessFull = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
        setName("Simple Interest"); // NOI18N
        setUndecorated(true);

        jLabel1.setText("ID");

        jLabel2.setText("First Name ");

        jLabel3.setText("Surname");

        jLabel4.setText("Service ");

        Inactive.setText("InActive");
        Inactive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InactiveActionPerformed(evt);
            }
        });

        Active.setSelected(true);
        Active.setLabel("Active");

        Deletlebtn.setText("Delete");
        Deletlebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletlebtnActionPerformed(evt);
            }
        });

        Insertbtn.setText("Insert");
        Insertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertbtnActionPerformed(evt);
            }
        });

        Updatebtn.setText("Update");
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });

        Selectbtn.setText("Select");
        Selectbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectbtnActionPerformed(evt);
            }
        });

        Allbtn.setLabel("All Customer");
        Allbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Selectbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Insertbtn)
                .addGap(18, 18, 18)
                .addComponent(Deletlebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(Updatebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Allbtn)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deletlebtn)
                    .addComponent(Insertbtn)
                    .addComponent(Updatebtn)
                    .addComponent(Selectbtn)
                    .addComponent(Allbtn))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Sbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "20 mb", "100 mb" }));
        Sbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstNametxt)
                                    .addComponent(Idtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Inactive)
                                .addGap(10, 10, 10)
                                .addComponent(Active)
                                .addGap(75, 75, 75))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(Sbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(Surnametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))))
                        .addGap(81, 81, 81)
                        .addComponent(SuccessFull))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SuccessFull))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FirstNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Surnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inactive)
                    .addComponent(Active))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InactiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InactiveActionPerformed

    private void SboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SboxActionPerformed

    private void DeletlebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletlebtnActionPerformed
        // TODO add your handling code here:
        if(Db.deletebyId(Integer.parseInt(Idtxt.getText())))
        {SuccessFull.setText("Record has been deletled");}
        else {SuccessFull.setText("Record was not deleted");}
    }//GEN-LAST:event_DeletlebtnActionPerformed

    private void SelectbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectbtnActionPerformed
       
        int id=  Integer.parseInt(Idtxt.getText());
        Customer customer = Db.RetrivebyId(id);
       
        Sbox.setSelectedIndex(customer.getService());
        FirstNametxt.setText(customer.getName());
        Surnametxt.setText(customer.getSurname());
        if(customer.getActive()== true)
        { Active.setSelected(true); }
        else if(customer.getActive()== false)
        {Inactive.setSelected(true);}
        SuccessFull.setText("Action as been complete");
        
    }//GEN-LAST:event_SelectbtnActionPerformed

    private void InsertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertbtnActionPerformed

       Customer customer = new Customer();
       Service services = new Service();
       Set<Service> service = new HashSet<>();
       
       if(Inactive.isSelected()==true) { customer.setActive(false); }
       else if(Active.isSelected()== true) {customer.setActive(true); }
       customer.setName(FirstNametxt.getText());
       customer.setSurname(Surnametxt.getText());
       
      services.setService( Sbox.getSelectedItem().toString());
      services.setId(Sbox.getSelectedIndex() + 1);
      customer.setService(Sbox.getSelectedIndex());
      service.add(services);
      
     if(Db.create(customer, service) == true)
     { SuccessFull.setText("Your Record has been created"); }
     else {SuccessFull.setText("Your creation was not successfull");}
     KeepCustomerCurrent();
     CurrentCustomer();
    }//GEN-LAST:event_InsertbtnActionPerformed

    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
        // TODO add your handling code here:
       if(Inactive.isSelected())
       { Db.updateById(Integer.parseInt(Idtxt.getText()), FirstNametxt.getText(),Surnametxt.getText(), Sbox.getSelectedIndex(),false);}
       else {Db.updateById(Integer.parseInt(Idtxt.getText()), FirstNametxt.getText(),Surnametxt.getText(), Sbox.getSelectedIndex(),true);}
       SuccessFull.setText("Update Was Successfull");
    }//GEN-LAST:event_UpdatebtnActionPerformed

    private void AllbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllbtnActionPerformed
        // TODO add your handling code here:  
       Customer c = CurrentCustomer();
       
        Idtxt.setText("" + c.getId());
        Sbox.setSelectedIndex(c.getService());
        FirstNametxt.setText(c.getName());
        Surnametxt.setText(c.getSurname());
        if(c.getActive()== true)
        { Active.setSelected(true); }
        else if(c.getActive()== false)
        {Inactive.setSelected(true);}
        
        if(Counter == 0) { Counter = customer.size(); }
        Counter--;
        KeepCustomerCurrent();
        CurrentCustomer();
    }//GEN-LAST:event_AllbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
           } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Active;
    private javax.swing.JButton Allbtn;
    private javax.swing.JButton Deletlebtn;
    private javax.swing.JTextField FirstNametxt;
    private javax.swing.JTextField Idtxt;
    private javax.swing.JRadioButton Inactive;
    private javax.swing.JButton Insertbtn;
    private javax.swing.JComboBox Sbox;
    private javax.swing.JButton Selectbtn;
    private javax.swing.JLabel SuccessFull;
    private javax.swing.JTextField Surnametxt;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
